services:
  ui:
    image: ghcr.io/mattrafuse/jetlag-ui:latest
    restart: unless-stopped
    expose:
      - "3000"

  server:
    image: ghcr.io/mattrafuse/jetlag-server:latest
    restart: unless-stopped
    environment:
      - PORT=3001
      - NODE_ENV=production
    expose:
      - "3001"

  nginx:
    image: ghcr.io/mattrafuse/jetlag-nginx:latest
    restart: unless-stopped
    depends_on:
      - ui
      - server
    ports:
      - "8080:80"
